version: '2'

services:

  sailsjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:1337
    volumes:
      - .:/usr/src/app

  mysqlsails:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mkcloud-sails
      MYSQL_USER: sails
      MYSQL_PASSWORD: sailsPowdj940
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: