version: '3.7'

services:

  sailsjs:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:1337
    volumes:
      - .:/usr/src/app
  mysqlsails:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mkcloud-sails
      MYSQL_USER: sails
      MYSQL_PASSWORD: sailsPowdj940
    volumes:
      - mysql-data:/var/lib/mysql

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
#    container_name: elasticsearch
#    environment:
#      - node.name=es01
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200

volumes:
  mysql-data:
